Blaze/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls', namespace='users')),
    path('posts/',include('posts.urls', namespace='posts')),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path(
        "post/<uuid:post_id>/<slug:post_slug>/",
        views.PostDetailView.as_view(),
        name="post_detail",
    ),
    path(
        "post/delete/<uuid:post_id>/", views.PostDeleteView.as_view(), name="post_delete"
    ),
    path(
        "post/update/<uuid:post_id>/", views.PostUpdateView.as_view(), name="post_update"
    ),
    path("post/create/", views.PostCreateView.as_view(), name="post_create"),
    path(
        "reply/<uuid:post_id>/<uuid:comment_id>/",
        views.PostAddReplyView.as_view(),
        name="add_reply",
    ),
    path("like/<uuid:post_id>/", views.PostLikeView.as_view(), name="post_like"),
]

users/urls.py
from django.urls import path
from users import views

app_name = "users"
urlpatterns = [
    path("register/", views.UserRegisterView.as_view(), name="user_register"),
    path("verify/", views.UserRegisterVerifyCodeView.as_view(), name="verify_code"),
    path("login/", views.UserLoginView.as_view(), name="user_login"),
    path("logout/", views.UserLogoutView.as_view(), name="user_logout"),
    path(
        "profile/<int:user_id>/", views.UserProfileView.as_view(), name="user_profile"
    ),
    path("edit_user/", views.EditUserProfileView.as_view(), name="edit_user"),
    path("follow/<int:user_id>/", views.UserFollowView.as_view(), name="user_follow"),
    path(
        "unfollow/<int:user_id>/",
        views.UserUnfollowView.as_view(),
        name="user_unfollow",
    ),
    # password reset process
    path("reset/", views.UserPasswordResetView.as_view(), name="reset_password"),
    path(
        "reset/done/",
        views.UserPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "confirm/<uidb64>/<token>/",
        views.UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "confirm/complete",
        views.UserPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'posts:home' %}">Home</a>
            {% if request.user.is_authenticated %}
            <a class="nav-link active" href="{% url 'users:user_profile' %}">Profile</a>
            <a class="nav-link active" href="{% url 'users:user_logout' %}">Logout</a>
            {% else %}
            <a class="nav-link active" href="{% url 'users:user_register' %}">Register</a>
            <a class="nav-link active" href="{% url 'users:user_login' %}">Login</a>
            {% endif %}
            {% comment %} {% if request.user.is_admin %}
            <a class="nav-link active" href="{% url 'home:  ' %}">   </a>
            {% endif %} {% endcomment %}
        </div>
    </div>
</nav>